apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: javawebapp
  name: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javawebapp
    spec:
      containers:
      - image: docker.io/sonu96/javawebapp
        name: javawebapp
        resources: {}
status: {}
